version: "3.9"
networks:
  appPdik:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: Webserver
    ports:
    - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
    - appPdik
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
    - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pdik
      MYSQL_USER:     app
      MYSQL_PASSWORD: Knoflook100
      MYSQL_ROOT_PASSWORD: Knoflook100!
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - appPdik
  php:
    build:
      context: .
      dockerfile: DockerPHP.yml
    container_name: php
    volumes:
    - .src:/var/www/html
    ports:
    - "9000:9000"
    networks:
      - appPdik

